import React, { useContext, useEffect } from 'react'
import './Body.css'
import { assets } from '../../assets/assets'
import { Context } from '../../context/context'

const Main = () => {

  const { onSent, recentPrompt, showResult, loading, resultData, setInput, input } = useContext(Context)

  // Handle Enter key press to send input
  useEffect(() => {
    const handleEnterPress = (event) => {
      if (event.key === 'Enter') {
        event.preventDefault(); // Prevent default form submission behavior
        onSent();
      }
    };

    // Add the event listener for "Enter" key press
    document.addEventListener('keypress', handleEnterPress);

    // Cleanup the event listener on component unmount
    return () => {
      document.removeEventListener('keypress', handleEnterPress);
    };
  }, [input, onSent]);

  return (
    <>
      <div className='body'>
        <div className="nav">
          <p>AIchatty</p>
          <img src={assets.user} alt="" />
        </div>

        <div className="body-container">

          {!showResult
            ?
            // if show result is not true
            <>
              <div className="greet">
                <p><span>Hello, Developer</span></p>
                <p>How can i help u today???</p>
              </div>

              <div className="cards">
                <div className="card" onClick={() => onSent("Can you explain the theory of relativity in simple terms?")}>
                  <p>Can you explain the theory of relativity in simple terms?</p>
                  <img src={assets.question} alt="" />
                </div>
                <div className="card" onClick={() => onSent("Write a dialogue between two characters who are stranded on a desert island")}>
                  <p>Write a dialogue between two characters who are stranded on a desert island</p>
                  <img src={assets.question} alt="" />
                </div>
                <div className="card" onClick={() => onSent("If two trains are traveling toward each other from different cities, how do you calculate when and where they will meet?")}>
                  <p>If two trains are traveling toward each other from different cities, how do you calculate when and where they will meet?</p>
                  <img src={assets.question} alt="" />
                </div>
                <div className="card" onClick={() => onSent("What are some tips for setting and achieving personal goals?")}>
                  <p>What are some tips for setting and achieving personal goals?</p>
                  <img src={assets.question} alt="" />
                </div>
              </div>
            </>
            :
            //if show result is true
            <div className='result'>
              {/* promt send by user */}
              <div className="result-title">
                <img src={assets.user} alt='user-icon' />
                <p>{recentPrompt}</p>
              </div>
              {/* response generated by ai */}
              <div className="result-data">
                <img src={assets.lightbulb} alt='' />

                {loading
                  ?
                  <div className='loader'>
                    <hr />
                    <hr />
                    <hr />
                  </div>
                  :
                  <p dangerouslySetInnerHTML={{ __html: resultData }}></p>
                }

              </div>
            </div>

          }



          <div className="body-bottom">
            <div className="search-box">
              <input onChange={(e) => setInput(e.target.value)} value={input} type="text" placeholder='Ask your question here' />
              <div>
                {input ? <img onClick={() => onSent()} src={assets.send} alt="" /> : null}
              </div>
            </div>

            <p className="bottom-info">AIchatty is a chatbot that can help you with any question you have. It may display inaccurate info, so double-cleck its responses.</p>
          </div>
        </div>
      </div>
    </>
  )
}

export default Main